First Project/app/views.py
import os, tempfile
from flask import Blueprint, render_template, request, jsonify, session, redirect, url_for, send_from_directory
from handlers.UserManagement import update_username, search_user_by_id, update_email
from handlers.UserManagement import get_user_role, compose_email_body, update_password
from handlers.UserManagement import search_user_by_email, validate_login, get_id_by_username
from handlers.UserManagement import search_user_by_username, send_recovery_password, create_user, get_orders_by_user_id
from handlers.ProductManagement import create_review, set_cart_item, update_product_after_order, register_order
from handlers.ProductManagement import create_product, remove_product, verify_id_exists, update_product_name, create_product_image
from handlers.ProductManagement import update_product_description, update_product_price, update_product_category, update_product_quantity
from handlers.EmailHandler import send_email_with_attachment, sql_to_pdf
from handlers.DataBaseCoordinator import check_database_table_exists, db_query
from handlers.Verifiers import check_username_exists, check_email_exists, check_product_in_cart
from handlers.Retrievers import get_all_products, get_product_by_id, get_product_reviews, get_cart, verify_product_id_exists, get_user_email



# Starting Blueprint
views = Blueprint('views', __name__)


# Check if the database tables exist
check_database_table_exists("users")
check_database_table_exists("products")
check_database_table_exists("reviews")
check_database_table_exists("all_orders")


# This route is used to serve the index page
@views.route('/', methods=['GET'])
def index():
    return render_template('index.html')


# This route is used to perform the login
@views.route('/login', methods=['GET','POST'])
def login():
    
    if request.method == "POST":
        # Get the password and username and email that were set in the signup session
        username = request.form.get("username")
        password = request.form.get("password")

        # Check if the username has a space
        if " " in username and len(username.split(" ")) == 2:

            # Merge the string into one username
            username = username.replace(" ", "")

        # Check if the username inserted is a email
        if "@" in username:

            # Search the username based on the email
            username = search_user_by_email(username)

        # Check if the login credentials are valid
        if validate_login(username, password) == True:
            # Set the session variables
            session["username"] = username
            session["id"] = get_id_by_username(username)
            session["admin"] = get_user_role(session["id"])
            check_database_table_exists(username.lower() + "_cart")
            check_database_table_exists(f"{username.lower()}_orders")

            return redirect(url_for("views.catalog", id=session["id"]))

    return render_template("login.html")

@views.route('/logout')
def logout():

    # Clear the session variables
    session.clear()

    # Return the login page
    return redirect(url_for("views.login"))


# This view is used to enroll new users into the platform
@views.route("/signup", methods=["GET", "POST"])
def signup():

    if request.method == "POST":
        # Get the username, password and email from the request
        username = request.form.get("username")
        password = request.form.get("password")
        email = request.form.get("email")

        # Check if there is no user in the database using the same email or the same username
        if search_user_by_email(email) != None or search_user_by_username(username) != None:

            # Return signup page if there is
            return render_template("signup.html", message="User already exists.")

        else:

            # Create the user in the database
            create_user(username, password, email)

            # Return the 2FA signup page, in order to validate the email
            return redirect(url_for("views.login"))
    else:
        return render_template("signup.html")
    

# This route is used to let the user reset he's password
@views.route("/reset-password", methods=["GET", "POST"])
def reset_password():

    # Check if the requested method is POST
    if request.method == "POST":

        # Get the user's email from the request
        email = request.form.get("email")

        # Get the username based on the email
        user = search_user_by_email(email)

        # Check if the user exists
        if user is None:

            # If the user doesn't exist, return the signup page
            return redirect(url_for("views.signup"))

        else:
            
            # Send recovery password to the user's email
            send_recovery_password(email)

            # Return the login page
            return redirect(url_for("views.login"))
    else:

        # If it isn't, return the same page
        return render_template("reset-password.html")
    

# This view returns the account settings page
@views.route("/profile/<username>")
def profile(username):
    
    # Get ID based on the username
    id = get_id_by_username(username)

    # Return the account settings page
    return render_template("profile.html", username=username, id=id)


# This view is used to check if te username exits
@views.route('/check_username', methods=['POST'])
def check_username():

    # Get the username from the request
    username = request.form.get('username')

    # Check if the username exists
    exists = check_username_exists(username)

    # Build response dictionary with the boolean
    response = {'exists': exists}

    # Return the response as a JSON object
    return jsonify(response)


# This view is used to check if te email exits
@views.route('/check_email', methods=['POST'])
def check_email():

    # Get the email from the request
    email = request.form.get('email')

    # Check if the username exists
    exists = check_email_exists(email)

    # Build response dictionary with the boolean
    response = {'exists': exists}

    # Return the response as a JSON object
    return jsonify(response)

# This view is used to check if te email exits
@views.route('/update_account/<id>', methods=['POST'])
def update_account(id):

    # Set the user's account image file path
    file_path = os.getcwd()+f"/database/accounts/{id}.png"

    # Get the new uploaded user's account image
    profile_photo = request.files.get("profile_photo")

    # If there is a image
    if profile_photo:

        # Save the image to the user's account
        profile_photo.save(file_path)

    # Get the username, email and password, from the user's session
    username = request.form.get("username")
    email = request.form.get("email")
    password = request.form.get("psw")

    # Check if the username field wasn't empty and occupied by another user
    if username != "" and not check_username_exists(username):

        # Update the username
        update_username(id, username)

        # Set the sessions username
        session["username"] = username

    else:

        # If there is a problem with the username, get the username based on the ID
        username = search_user_by_id(id)[1]

    # Check if the email field wasn't empty and occupied by another user
    if email != "" and not check_email_exists(email):

        # Update the email
        update_email(id, email)

    else:

        # If there is a problem with the username, get the username based on the ID
        email = search_user_by_id(id)[3]

    # Check if the password wasn't empty
    if password != "":

        # Update the password
        update_password(id, password)
    
    # Return the profile page
    return redirect(url_for("views.catalog", id=id))


# This view is used to get a image
@views.route('/get_image/<path:filename>')
def get_image(filename):

    # Send the image
    path = "/".join(filename.split("/")[:-1])
    filename = filename.split("/")[-1]
    return send_from_directory(path, filename)


@views.route('/catalog/<id>')
def catalog(id):
    
        # Get the username and id from the session
        name = session.get("username")
        admin = session.get("admin")

        if admin:
            return render_template("catalog_admin.html", username=name, id=id, admin=admin)
        else:
            # Return the catalog page
            return render_template("catalog.html", username=name, id=id, admin=admin)


@views.route('/products')
def products():

    products = get_all_products()

    return jsonify(products)


@views.route('/add_product/<id>', methods=['POST'])
def add_product(id):

    product_name = request.form.get("productName")
    product_description = request.form.get("productDescription")
    product_price = request.form.get("productPrice")
    product_category = request.form.get("productCategory")
    product_quantity = request.form.get("productUnits")
    product_photo = request.files.get("productImage")

    create_product(product_name, product_description, product_price, product_category, product_quantity, product_photo)


    return redirect(url_for("views.catalog", id=session["id"]))


@views.route('/remove_product/<id>', methods=['POST'])
def remove_product_by_id(id):
    # Updated route name and parameter name to avoid conflicts
    product_id = request.form.get("productId")

    # Assuming 'remove_product' is a function you've defined elsewhere, you can use it here
    product = remove_product(product_id)

    return redirect(url_for("views.catalog", id=session["id"]))


@views.route('/edit_product/<id>', methods=['POST'])
def edit_product_by_id(id):

    product_id = request.form.get("productId")
    product_name = request.form.get("productName")
    product_description = request.form.get("productDescription")
    product_price = request.form.get("productPrice")
    product_category = request.form.get("productCategory")

First Project/app/templates/catalog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Catalog</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/catalog.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/nouislider@14.6.4/distribute/nouislider.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/nouislider@14.6.4/distribute/nouislider.min.js"></script>
</head>
<body>
    <header>
        <h1>Product Catalog</h1>
        <button class="logout-button" id="logoutButton">Logout</button>
        <!-- Profile and Orders links -->
        <div class="profile-links">
            <a href="/profile/{{username}}" id="profileLink">
                <img src="{{ url_for('views.get_image', filename='database/accounts/' + id + '.png') }}" alt="Profile Photo">
                <span id="username">{{username}}</span>
            </a>
            <a href="/orders/{{id}}" id="ordersLink">Orders</a>
        </div>

        <input type="text" id="searchInput" placeholder="Search products">
        <select id="categoryFilter">
            <option value="all">All Categories</option>
            <option value="electronics">Electronics</option>
            <option value="clothing">Clothing</option>
            <option value="footwear">Footwear</option>
            <option value="kitchen">Kitchen</option>
            <option value="accessories">Accessories</option>
            <option value="furniture">Furniture</option>
            <option value="software">Software</option>
            <option value="fitness">Fitness</option>
            <option value="outdoors">Outdoors</option>
            <!-- Add more categories as needed -->
        </select>
        <select id="sortOrder">
            <option value="asc">Price: Low to High</option>
            <option value="desc">Price: High to Low</option>
        </select>
        <div class="price-slider" id="priceSlider"></div>
        <br>
        <span id="minMaxPriceLabel">Price Range: €0 - €1000</span>
    </header>
    <div class="product-list">
        <!-- Product listings will be displayed here -->
    </div>
    <div class="shopping-cart">
        <h2>Shopping Cart</h2>
        <ul id="cartList">
            <!-- Cart items will be displayed here -->
        </ul>
        <p id="cartTotal">Total: <span id="totalAmount">0 €</span></p>
        <button id="removeAllItems">Clear the Cart</button>
        <button id="checkoutButton">Checkout</button>
    </div>

    <script type="text/javascript" src="{{url_for('static', filename='js/catalog.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/catalog_cart.js')}}"></script>
    <script>
        // Call the function to update the cart display when the page loads
        updateCartDisplay();
    </script>
</body>
</html>

First Project/app/templates/catalog_admin.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Admin Dashboard</title>
        <link rel="stylesheet" href="{{url_for('static', filename='css/catalog_admin.css')}}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/nouislider@14.6.4/distribute/nouislider.min.css">
        <script src="https://cdn.jsdelivr.net/npm/nouislider@14.6.4/distribute/nouislider.min.js"></script>
    </head>
    <body>
        <header>
            <h1>Admin Dashboard</h1>
            <nav>
                <ul>
                    <li><a href="/catalog/{{id}}">Home</a></li>
                    <li><a href="#">Inventory Management</a>
                        <ul>
                            <li><a id="add_product">Add Product</a></li>
                            <li><a id="remove_product">Remove Product</a></li>
                            <li><a id="edit_product">Edit Product</a></li>
                            <li><a href="/product-quantities/{{id}}">Manage Quantities</a></li>
                        </ul>
                    </li>
                    <li><button class="logout-button" id="logoutButton">Logout</button></li>
                    <li><a href="/profile/{{username}}" id="profileLink">
                        <img src="{{ url_for('views.get_image', filename='database/accounts/' + id + '.png') }}" alt="Profile Photo">
                        <span id="username">{{username}}</span>
                    </a></li>
                    
                </ul>
            </nav>
        </header>

        <h1>Product Catalog</h1>
        <input type="text" id="searchInput" placeholder="Search products">
        <select id="categoryFilter">
            <option value="all">All Categories</option>
            <option value="electronics">Electronics</option>
            <option value="clothing">Clothing</option>
            <option value="footwear">Footwear</option>
            <option value="kitchen">Kitchen</option>
            <option value="accessories">Accessories</option>
            <option value="furniture">Furniture</option>
            <option value="software">Software</option>
            <option value="fitness">Fitness</option>
            <option value="outdoors">Outdoors</option>
            <!-- Add more categories as needed -->
        </select>

        <select id="stockSelect">
            <option value="inStock">In Stock</option>
            <option value="outStock">Out of Stock</option>
            <!-- Add more categories as needed -->
        </select>

        <select id="sortOrder">
            <option value="asc">Price: Low to High</option>
            <option value="desc">Price: High to Low</option>
        </select>
        <div class="price-slider" id="priceSlider"></div>
        <br>
        <span id="minMaxPriceLabel">Price Range: €0 - €1000</span>    

        <div class="product-container">
            <div class="product-list">
                <!-- Product listings will be displayed here -->
            </div>
        </div>

        <!-- Add Product Popup -->
        <div id="addProductPopup" class="popup">
            <div class="popup-content">
                <span class="close" onclick="closePopup('addProductPopup')">&times;</span>
                <h2>Add Product</h2>
                <form id="productForm" action="/add_product/{{id}}" method="post" enctype="multipart/form-data">
                    <label for="productName">Name:</label>
                    <input type="text" id="productName" name="productName" required>
                
                    <label for="productPrice">Price:</label>
                    <input type="number" id="productPrice" name="productPrice" step="any">
                
                    <label for="productDescription">Description:</label>
                    <textarea id="productDescription" name="productDescription" rows="4" required></textarea>
                
                    <label for="productCategory">Category:</label>
                    <select id="categoryFilter" name="productCategory">
                        <option value="electronics">Electronics</option>
                        <option value="clothing">Clothing</option>
                        <option value="footwear">Footwear</option>
                        <option value="kitchen">Kitchen</option>
                        <option value="accessories">Accessories</option>
                        <option value="furniture">Furniture</option>
                        <option value="software">Software</option>
                        <option value="fitness">Fitness</option>
                        <option value="outdoors">Outdoors</option>
                        <!-- Add more categories as needed -->
                    </select>

                    <label for="productUnits">Number of Units:</label>
                    <input type="number" id="productUnits" name="productUnits" required>
                
                    <label for="productImage">Image:</label>
                    <input type="file" id="productImage" name="productImage" accept="image/*" required>
                
                    <button type="submit">Add</button>
                </form>                
            </div>
        </div>

        <!-- Remove Product Popup -->
        <div id="removeProductPopup" class="popupRemove">
            <div class="popup-contentRemove">
                <span class="closeRemove" onclick="closePopup('removeProductPopup')">&times;</span>
                <h2>Remove Product</h2>
                <form id="productForm" action="/remove_product/{{id}}" method="post" enctype="multipart/form-data">
                    <label for="productId">Name:</label>
                    <input type="text" id="productId" name="productId" required>
                    <button type="submit">Remove</button>
                </form>                
            </div>
        </div>


        <!-- Edit Product Popup -->
        <div id="editProductPopup" class="popupEdit">
            <div class="popup-contentEdit">
                <span class="close" onclick="closePopup('editProductPopup')">&times;</span>
                <h2>Edit Product</h2>
                <form id="productForm" action="/edit_product/{{id}}" method="post" enctype="multipart/form-data">

                    <label for="productId">Id:</label>
                    <input type="text" id="productId" name="productId" required>

                    <label for="productName">Name:</label>
                    <input type="text" id="productName" name="productName">
                
                    <label for="productPrice">Price:</label>
                    <input type="number" id="productPrice" name="productPrice" step="any">
                
                    <label for="productDescription">Description:</label>
                    <textarea id="productDescription" name="productDescription" rows="4"></textarea>
                
                    <label for="productCategory">Category:</label>
                    <select id="categoryFilter" name="productCategory">
                        <option value="">Choose Category</option>
                        <option value="electronics">Electronics</option>
                        <option value="clothing">Clothing</option>
                        <option value="footwear">Footwear</option>
                        <option value="kitchen">Kitchen</option>
                        <option value="accessories">Accessories</option>
                        <option value="furniture">Furniture</option>
                        <option value="software">Software</option>
                        <option value="fitness">Fitness</option>
                        <option value="outdoors">Outdoors</option>
                        <!-- Add more categories as needed -->
                    </select>
                    <label for="productUnits">Number of Units:</label>
                    <input type="number" id="productUnits" name="productUnits">
                
                    <label for="productImage">Image:</label>
                    <input type="file" id="productImage" name="productImage" accept="image/*">
                
                    <button type="submit">Edit</button>
                </form>                
            </div>
        </div>
        

        
        <script type="text/javascript" src="{{url_for('static', filename='js/catalog_admin.js')}}"></script>
    </body>
</html>

First Project/app/templates/order_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thank You</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/order_confirm.css')}}">
</head>
<body>
    <h1>Thank You for Your Purchase!</h1>
    
    <div class="thank-you-message">
        <p>Your order has been successfully placed.</p>
        <p>An email confirmation with order details has been sent to your email address.</p>
        <p>If you have any questions or need further assistance, please feel free to contact our support team.</p>
    </div>

    <div class="back-to-home">
        <a href="/catalog/{{id}}">Return to Home Page</a>
    </div>
</body>
</html>

First Project/app/templates/orders.html
<!DOCTYPE html>
<html>
<head>
    <title>Orders</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/catalog.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/orders.css')}}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
</head>
<body>
    <h1>Orders</h1>
    <!-- Add a search bar above the table -->
    <div class="container mt-3">
        <input type="text" id="searchInput" placeholder="Search products">
    </div>

    <div class="container mt-5">
        <table class="table table-striped" id="productTable">
            <thead>
                <tr>
                    <th data-column="image">Image</th> <!-- New column for product images -->
                    <th data-column="id">Order ID</th>
                    <th data-column="id">Product ID</th>
                    <th data-column="name">Name</th>
                    <th data-column="description">Quantity</th>
                    <th data-column="price">Price (€)</th>
                    <th data-column="category">Date</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td><img src="{{ url_for('views.get_image', filename='catalog/' + product.product_id|string + '.png') }}" width="50"></td>
                        <td>{{ product.order_id }}</td>
                        <td>{{ product.product_id }}</td>
                        <td>{{ product.name }}</td>
                        <td>{{ product.quantity }}</td>
                        <td>{{ product.price }} €</td>
                        <td>{{ product.date }}</td>
                        <td><i class="fas fa-cart-plus reorderButton cart-button" data-product='{{ product|tojson|safe }}' id="reorderButton"></i></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="shopping-cart">
            <h2>Shopping Cart</h2>
            <ul id="cartList">
                <!-- Cart items will be displayed here -->
            </ul>
            <p id="cartTotal">Total: <span id="totalAmount">0 €</span></p>
            <button id="removeAllItems">Clear the Cart</button>
            <button id="checkoutButton">Checkout</button>
        </div>
    </div>
    <script type="text/javascript" src="{{url_for('static', filename='js/product_quantities.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/orders.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/catalog_cart.js')}}"></script>
    <script>
        // Call the function to update the cart display when the page loads
        updateCartDisplay();
    </script>
</body>
</html>

First Project/app/templates/product_quantities.html
<!DOCTYPE html>
<html>
<head>
    <title>Product Quantities</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        /* Add pointer cursor to table headers on hover */
        #productTable thead th {
            cursor: pointer;
        }
        /* Style for sorting indicators */
        .sorting-asc::after {
            content: "▲";
            padding-left: 5px;
        }
        .sorting-desc::after {
            content: "▼";
            padding-left: 5px;
        }
    </style>
</head>
<body>
    <h1>Product Quantities</h1>
    <!-- Add a search bar above the table -->
    <div class="container mt-3">
        <input type="text" id="searchInput" placeholder="Search products">
    </div>

    <div class="container mt-5">
        <table class="table table-striped" id="productTable">
            <thead>
                <tr>
                    <th data-column="image">Image</th> <!-- New column for product images -->
                    <th data-column="id">ID</th>
                    <th data-column="name">Name</th>
                    <th data-column="description">Description</th>
                    <th data-column="price">Price (€)</th>
                    <th data-column="category">Category</th>
                    <th data-column="stock">Stock</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td><img src="{{ url_for('views.get_image', filename='catalog/' + product.id|string + '.png') }}" width="50"></td>
                        <td>{{ product.id }}</td>
                        <td>{{ product.name }}</td>
                        <td>{{ product.description }}</td>
                        <td>{{ product.price }} €</td>
                        <td>{{ product.category }}</td>
                        <td>{{ product.stock }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script type="text/javascript" src="{{url_for('static', filename='js/product_quantities.js')}}"></script>
</body>
</html>

First Project/app/templates/profile.html
<!DOCTYPE html>
<html lang="en" class="dark" style="color-scheme: dark;">
<head>
    <meta charset="UTF-8">
    <title>ECO - Account Settings</title>
    <link rel="icon" type="image/png" href="{{ url_for('views.get_image', filename='database/accounts/' + id + '/' + id + '.png') }}"/>
    <link rel="stylesheet" href="{{url_for('static', filename='css/profile.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/home.css')}}">
    <script type="text/javascript" src="{{url_for('static', filename='js/profile.js')}}"></script>
</head>
<body style="margin-top: 7%;">
<h2>Account Settings</h2>
<img src="{{ url_for('views.get_image', filename='database/accounts/' + id + '.png') }}" alt="Profile Photo" class="profile-image" style="margin-top: 70px;">
<h2>{{username}}</h2>
    <form action="/update_account/{{id}}" method="post" enctype="multipart/form-data" onsubmit="return validateForm();" style="margin-top: 70px;">
        <div class="container">
            <label for="username"><b>Username</b></label>
            <input type="text" placeholder="Enter Username" name="username" id="username" style="margin-bottom: 30px; width: 200px; display: block; margin-left: 39%;">

            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="email" id="email" style="margin-bottom: 30px; width: 200px; display: block; margin-left: 39%;">

            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="psw" id="psw" style="margin-bottom: 30px; width: 200px; display: block; margin-left: 39%;">

            <label for="psw-repeat"><b>Repeat Password</b></label>
            <input type="password" placeholder="Repeat Password" name="psw-repeat" id="psw-repeat" style="margin-bottom: 30px; width: 200px; display: block; margin-left: 39%;">
            <div id="error-message-psw" style="color: red;"></div>
            <div id="error-message-username" style="color: red;"></div>
            <div id="error-message-email" style="color: red;"></div>

            <label for="profile_photo"><b>Profile Photo</b></label>
            <br>
            <label class="image-label">
                Insert<input type="file" name="profile_photo" accept="image/*" onchange="previewImage();" capture="camera" class="image-input">
            </label>
            <br>
            <img src="" alt="Preview Image" class="preview-image">
            <br>
            <br>
            <button type="submit" style="height: fit-content;" class="savebtn">Save</button>
            <button type="button" style="height: fit-content;" class="cancelbtn" onclick='goToCatalogPage("{{id}}")'>Cancel</button>
        </div>
    </form>
</body>
</html>